In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [25]:
input_layer_len = 2
hidden_layer_len = 3
output_layer_len = 1

In [56]:
# test set 
input_data = np.array([[0,0],[1,0.1],[0,1],[1,1]])
target_data = np.array([[0],[1],[1],[0]])

In [57]:
input_layer = input_data[1]

In [58]:
input_layer

array([1. , 0.1])

In [68]:
hidden_layer = np.random.rand(input_layer_len, hidden_layer_len)

In [69]:
hidden_layer

array([[0.84785463, 0.20503922, 0.47851958],
       [0.3219915 , 0.39841792, 0.8831111 ]])

In [70]:
output_layer = np.random.rand(hidden_layer_len, output_layer_len)

In [71]:
output_layer

array([[0.21894029],
       [0.32180354],
       [0.55430461]])

In [86]:
temp = input_layer.dot(hidden_layer)
print(temp)

[0.88005378 0.24488102 0.56683069]


In [87]:
output = temp.dot(output_layer)
print(output)

[0.58567968]


In [88]:
(0.88005378*0.21894029+0.24488102*0.32180354+0.55430461*0.56683069)

0.5856796734800879

In [97]:
# cost
1/2*len(input_data)*np.sum([(input_data[i].dot(hidden_layer).dot(output_layer) - target_data[i])**2 for i in range(len(input_data))])

3.442166082096365