In [2]:
import numpy as np
import scipy.special as spe
import matplotlib.pyplot as plt
%matplotlib inline

class NN:
    def __init__(self,inputnodes, hiddennodes, outputnodes, learningrate):
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes
        
        self.lr = learningrate
        
        self.w_ih = np.random.normal(0.0, pow(self.hnodes, -0.5), (self.hnodes, self.inodes))
        self.w_ho = np.random.normal(0.0, pow(self.onodes, -0.5), (self.onodes, self.hnodes))
    
    def act_func(self, x):
        return 1/(1+np.exp(-x))
    
    def train(self, inputs_list, targets_list):
        inputs = np.array(inputs_list, ndmin=2).T
        targets = np.array(targets_list, ndmin=2).T
        
        hidden_inputs = np.dot(self.w_ih, inputs)
        hidden_outputs = self.act_func(hidden_inputs)
        
        final_inputs = np.dot(self.w_ho, hidden_outputs)
        final_outputs = self.act_func(final_inputs)
        
        # hidden과 output 사이
        output_errors = targets - final_outputs
        
        # input과 hidden 사이
        hidden_errors = np.dot(self.w_ho.T, output_errors)
        
        self.w_ho += self.lr * np.dot((output_errors * final_outputs * (1.0 - final_outputs)), hidden_outputs.T)
        self.w_ih += self.lr * np.dot((hidden_errors * hidden_outputs * (1.0 - hidden_outputs)), inputs.T)
        
        
    def query(self, input_list):
        inputs = np.array(input_list, ndmin=2).T
        
        hidden_inputs = np.dot(self.w_ih, inputs)
        hidden_outputs = self.act_func(hidden_inputs)
        
        final_inputs = np.dot(self.w_ho, hidden_outputs)
        final_outputs = self.act_func(final_inputs)
        
        return final_outputs

In [86]:

# 숫자들에서 원모양 수를 학습
input_data = np.array([[7,1,1,1],[8,8,0,9],[2,1,7,2],[6,6,6,6],[1,1,1,1],
               [2,2,2,2],[7,6,6,2],[9,3,1,3],[0,0,0,0],[5,5,5,5],
               [8,1,9,3],[8,0,9,6],[4,3,9,8],[9,4,7,5],[9,0,3,8],
               [3,1,4,8],          [6,0,6,0]])

target_data_temp = np.array([0,6,0,4,0,0,2,1,4,0,3,5,3,1,4,2,
                            4])

i = 4
h = 17
o = 8

l = 0.05

nn = NN(i,h,o,l)

# for i in range(16):
#     print(input_data[i],target_data_temp[i])

input_data = input_data
target_data = np.zeros((len(input_data),o))

for i in range(len(target_data)):
    target_data[i,target_data_temp[i]] = 1
#print(target_data)

for _ in range(5000):
        for i in range(len(input_data)):
            nn.train(input_data[i],target_data[i])
        for i in range(len(input_data)-1,-1,-1):
            nn.train(input_data[i],target_data[i])
            
rate = 0
for k in range(len(input_data)):
    test = input_data[k]
    print("################################")
    print("input : " , test)
    print("target : ", target_data_temp[k])
    print("output : ", np.argmax(nn.query(test)))
    print(nn.query(test))
    
    if np.argmax(nn.query(test))== target_data_temp[k]:
        rate += 1
        
print("################################")
print("training completion rate : ",(rate/len(input_data))*100,'%')

################################
input :  [7 1 1 1]
target :  0
output :  0
[[  9.53751328e-01]
 [  2.65871793e-02]
 [  1.63739395e-04]
 [  8.85187540e-05]
 [  4.54954912e-02]
 [  2.72649177e-03]
 [  6.14867963e-04]
 [  1.95829475e-03]]
################################
input :  [8 8 0 9]
target :  6
output :  6
[[  1.27649137e-02]
 [  6.06029472e-03]
 [  4.77494901e-02]
 [  9.90522625e-04]
 [  4.77811558e-02]
 [  7.36690318e-06]
 [  9.46412737e-01]
 [  8.15600432e-04]]
################################
input :  [2 1 7 2]
target :  0
output :  0
[[  9.85009949e-01]
 [  1.91020952e-03]
 [  2.56217061e-05]
 [  3.49482658e-02]
 [  1.98695305e-02]
 [  1.15344543e-02]
 [  5.04000342e-06]
 [  6.16294100e-03]]
################################
input :  [6 6 6 6]
target :  4
output :  0
[[  4.93322951e-01]
 [  2.39646256e-02]
 [  9.12739871e-03]
 [  6.74085274e-03]
 [  4.65929893e-01]
 [  6.49544980e-05]
 [  2.76741525e-02]
 [  1.08741414e-03]]
################################
input :  [1 1 1 1]
